# Generated by Django 4.2.2 on 2023-06-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobofferinfo',
            name='offer_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
