# Generated by Django 4.2.2 on 2023-06-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobofferinfo',
            name='offer_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
