# Generated by Django 4.2.2 on 2023-06-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_jobofferinfo_offer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobofferinfo',
            name='connects_to_apply',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
