# Generated by Django 4.2.2 on 2023-07-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0007_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
